CREATE SERVICE mlflow_service
  IN COMPUTE POOL <your_compute_node_pool>
  FROM SPECIFICATION $$
    spec:
      containers:
      - name: mlflow
        image: <your_docker_image_name>
        env:
          SERVER_PORT: 5000
        readinessProbe:
          port: 5000
          path: /healthcheck
      endpoints:
      - name: mlflowendpoint
        port: 5000
        public: true
      $$
   MIN_INSTANCES=1
   MAX_INSTANCES=1;
